In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
 #Split method using in String
 s = "Hiiii there Divya..!!!"
 s.split()

['Hiiii', 'there', 'Divya..!!!']

In [ ]:
#Use.format() in String and get output
planet = "Earth"
diameter = 12742
output ="The diameter of {planet} is {diameter} kilometers".format(planet="Earth",diameter=12742)
output

'The diameter of Earth is 12742 kilometers'

In [ ]:
#Nest Dictionary
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [ ]:
#Array of 10 zeros
import numpy as St

np=St.zeros(10)
print("Array of 10 zeros = ",np)

Array of 10 zeros =  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [ ]:
#Array of 10 five's
import numpy as St

np=St.ones(10)*5
print("Array of 10 five's = ",np)

Array of 10 five's =  [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

In [ ]:
#even integers from 20 to 35
import numpy as St

np=St.arange(20,35,2)
print("Array integers even numbers = ",np)

Array integers even numbers =  [20 22 24 26 28 30 32 34]

In [ ]:
# Matrix of 3*3 with values range form 0,8

import numpy as St

np=St.arange(0,9).reshape(3,3)
print("Matrix of 3*3")
print(np)

Matrix of 3*3
[[0 1 2]
 [3 4 5]
 [6 7 8]]

In [ ]:
#concatenate function

import numpy as St
a=St.array([1,2,3])
b=St.array([4,5,6])
np=St.concatenate((a,b))
print("Total value = ",np)

Total value =  [1 2 3 4 5 6]

In [ ]:
#Create a Dataframe with 3 rows & 2 coloumns

import pandas as St

s1=[['a',1],['b',2],['c',3]]
St.DataFrame(s1,columns=['variables','values'])

  variables  values
0         a       1
1         b       2
2         c       3

In [ ]:
#Genearate the series of dates From 1st jan,2023 to 10th feb,2023

import pandas as St

St.date_range(start='01-01-2023',end='02-10-2023')

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
#create 2D list to DataFrame

import pandas as St

lists = [[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
St.DataFrame(lists,columns=['numbers','letters','values'])

   numbers letters  values
0        1     aaa      22
1        2     bbb      25
2        3     ccc      24